### ISSUE TITLE
Seeking New Ownership!

### ISSUE THREAD

**Issue by geekdave** [GruntBlanketMocha/grunt-blanket-mocha#39]
This project is no longer actively maintained.  If you are interested in taking it over, please comment below.  Highlight any contributions you have made to the project, as well as any other examples of your open source work.  Thanks!

**Comment by abbakym** [comment]
Hi @geekdave, I think I would try that. Has no experience so far in maintaining an OSS project, but would be glad to =)
I'm using your project at work for a few pipelines, and have recently contributed a pull request (https://github.com/ModelN/grunt-blanket-mocha/pull/37). Next thing on my list would be adding ability to generate coverage report as a file for integration with CI tools (basic prototype is already in my fork).
Regarding "other examples of your open source work", I think it's all visible in my public Github profile =)

Regards,
Georgii

**Comment by geekdave** [comment]
@abbakym Thanks for volunteering!  I've added you to the maintainers group, so you should have push access and the ability to merge PRs.

I'll leave this issue open in case anyone is interested in co-maintaining.

**Comment by abbakym** [comment]
Thanks @geekdave !

**Comment by eugenet8k** [comment]
Hey guys, I made a fork and with an update to PhantomJS 2.x here https://github.com/eugenet8k/grunt-mocha-blanket

**Comment by givankin** [comment]
Hi @eugenet8k , good job! Can you submit a PR? It seems a good idea to give that update to all users.

**Comment by eugenet8k** [comment]
@givankin oh, sure I can. I though this repo is not supported anymore so I continued updating it in my fork. But if there is a maintainer I would be happy to send PRs for a review.

**Comment by givankin** [comment]
@eugenet8k I can merge it. I am not very active at maintaining this project, but I use it myself and am always ready to merge a good pr.

**Comment by givankin** [comment]
hey @eugenet8k, I just checked the upstream project and it seems they have it covered already. So perhaps I will just merge the changes from there, hopefully it will solve the issue for you as well. I will try doing that in nearest days and will let you know. Thanks for your effort anyways!

**Comment by givankin** [comment]
Hi @geekdave, I (finally!) made some notable changes to the code. However, push seems to be blocked for me:
```
remote: Permission to GruntBlanketMocha/grunt-blanket-mocha.git denied to givankin.
```

Could you assist?

**Comment by geekdave** [comment]
Hi @givankin - My apologies for the delay!  I had you on the maintainers team but hadn't granted that team access to this repo.  Should work now!

**Comment by andrewhood125** [comment]
@geekdave I'd be happy to help as well. @givankin looks like you updated the master branch of your fork with phantomjs2 support. Do you want create the PR?

**Comment by givankin** [comment]
hi @andrewhood125 i didn't, it's been pending, got caught in other stuff. will do this weekend.

**Comment by givankin** [comment]
@andrewhood125 I've just committed the changes. New version (0.5.0) uses Phantom 2.

**Comment by fernandomora** [comment]
There is some estimation on when the v1.0.0 version will be tagged and released?

**Comment by givankin** [comment]
Well, I am now the maintainer. If someone else wants to volunteer, let me know.
