### ISSUE TITLE
Tag and release to NPM version 1.0.0

### ISSUE THREAD

**Issue by fernandomora** [GruntBlanketMocha/grunt-blanket-mocha#41]
It would be great to tag the version and release to NPM all the changes made since March 2015.
The upgrade to PhantomJS 2 is required to be able to use it in macOS Sierra: https://github.com/ariya/phantomjs/issues/14558
Thank you for your work 😄

**Comment by givankin** [comment]
@fernandomora I don't have access to npm yet. @geekdave can you grant me access to the package on npm? I am givankin there.

**Comment by geekdave** [comment]
Sorry for the delay!  Just added givankin as a maintainer on npm.

**Comment by givankin** [comment]
Version 1.0.0 is in the registry. Sorry for the delay :)
